# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=b'\xed\x86\xb5\xec\x9d\xb8\xec\x8b\x9c\xec\x9e\xa5 \xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd\xec\xa7\x91 \xec\x9d\xb4\xeb\xa6\x84', max_length=200)),
                ('location', models.CharField(default=b'\xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd\xec\xa7\x91 \xec\x9c\x84\xec\xb9\x98', max_length=200)),
                ('telephone', models.CharField(default=b'\xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd\xec\xa7\x91 \xec\x97\xb0\xeb\x9d\xbd\xec\xb2\x98', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2016, 5, 6, 9, 8, 39, 897092, tzinfo=utc), verbose_name=b'Published Date')),
                ('taste', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('service', models.IntegerField(default=0)),
                ('air', models.IntegerField(default=0)),
                ('cleanness', models.IntegerField(default=0)),
                ('count_taste', models.IntegerField(default=0)),
                ('count_price', models.IntegerField(default=0)),
                ('count_service', models.IntegerField(default=0)),
                ('count_air', models.IntegerField(default=0)),
                ('count_cleanness', models.IntegerField(default=0)),
                ('review', models.CharField(default=b'100\xec\x9e\x90 \xed\x8f\x89', max_length=200)),
            ],
        ),
    ]
