# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0002_auto_20160506_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='location',
            field=models.CharField(default=b'\xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd\xec\xa7\x91 \xec\x9c\x84\xec\xb9\x98', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 9, 10, 38, 588847, tzinfo=utc), verbose_name=b'Published Date'),
        ),
    ]
