# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0003_auto_20160506_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'\xec\x82\xac\xec\x9a\xa9\xec\x9e\x90', max_length=100)),
                ('count_taste', models.IntegerField(default=0)),
                ('count_price', models.IntegerField(default=0)),
                ('count_service', models.IntegerField(default=0)),
                ('count_air', models.IntegerField(default=0)),
                ('count_cleanness', models.IntegerField(default=0)),
                ('rep_date', models.DateTimeField(default=datetime.datetime(2016, 5, 6, 13, 14, 54, 349297, tzinfo=utc), verbose_name=b'Replied Date')),
                ('reple', models.CharField(default=b'100\xec\x9e\x90 \xed\x8f\x89', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_air',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_cleanness',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_price',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_service',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_taste',
        ),
        migrations.AddField(
            model_name='question',
            name='replier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 13, 14, 54, 348169, tzinfo=utc), verbose_name=b'Published Date'),
        ),
        migrations.AddField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosirak.Question'),
        ),
    ]
