# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0005_auto_20160506_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='air',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='cleanness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 21, 34, 35, 578434, tzinfo=utc), verbose_name=b'Published Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='service',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='taste',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='rep_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 21, 34, 35, 579653, tzinfo=utc), verbose_name=b'Replied Date'),
        ),
    ]
