# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0006_auto_20160506_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 7, 42, 58, 550601, tzinfo=utc), verbose_name=b'Published Date'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='rep_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 7, 42, 58, 551571, tzinfo=utc), verbose_name=b'Replied Date'),
        ),
    ]
